- utils-kotlin/build.gradle.kts
See https://docs.gradle.org/7.1.1/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main
> Fix Gradle warning about deprecated property JavaExec.main

- LICENSE
- LICENSE_HEADER
A valid license is required for [compliance reasons](https://jira.sonarsource.com/browse/BUILD-1273).
Contact Release Engineering Team for more information.
> fix(BUILD-1337): fix license

- kotlin-checks-test-sources/src/main/kotlin/checks/DuplicateBranchCheckSample.kt
- sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/api/ApiExtensions.kt
- sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/checks/DuplicateBranchCheck.kt
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/api/ApiExtensionsKtTest.kt
> SONARKT-202 S1871 should not consider two method calls the same if they're calling different methods with the same name

- wss-unified-agent.config
Default to excluding test and provided dependencies
> Mend: Update configuration to reduce FPs

- build.gradle.kts
- its/ruling/build.gradle.kts
- sonar-kotlin-plugin/build.gradle.kts
- utils-kotlin/README.md
- utils-kotlin/src/main/kotlin/org/sonarsource/kotlin/ast/AstPrinter.kt
- utils-kotlin/src/main/kotlin/org/sonarsource/kotlin/externalreport/ExternalRule.kt
- utils-kotlin/src/test/kotlin/org/sonarsource/kotlin/ast/AstPrinterTest.kt
- utils-kotlin/src/test/kotlin/org/sonarsource/kotlin/externalreport/ExternalReportTest.kt
- utils-kotlin/src/test/kotlin/org/sonarsource/kotlin/externalreport/androidlint/AndroidLintDefinitionTest.kt
- utils-kotlin/src/test/kotlin/org/sonarsource/kotlin/externalreport/detekt/DetektRuleDefinitionGeneratorTest.kt
- utils-kotlin/src/test/kotlin/org/sonarsource/kotlin/externalreport/ktlint/KtlintRuleDefinitionGeneratorTest.kt
* Update spotless to the latest version 6.11.0
* configure spotless for all modules except kotlin-checks-test-sources
> SONARKT-235 Improve spotless configuration

- .cirrus.yml
- .github/workflows/dogfood.yml
- .github/workflows/release.yml
- .gitmodules
> BUILD-2114 Use Vault

- sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/plugin/KotlinPlugin.kt
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/KotlinSensorTest.kt
> SONARKT-276 Fallback to latest stable Kotlin version instead of hardcoded Kotlin 1.5

- gradle/wrapper/gradle-wrapper.properties
See https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification
> Enable checksum verification of Gradle distribution

- sonar-kotlin-gradle/build.gradle.kts
- sonar-kotlin-metrics/build.gradle.kts
- sonar-kotlin-plugin/build.gradle.kts
- utils-kotlin/build.gradle.kts
This was overlooked in 7f85757d28c80581caec8c0b9fc9ebb01677fa32.
> Remove obsolete code

- gradle/verification-metadata.xml
See https://docs.gradle.org/current/userguide/dependency_verification.html
----
Depends on
* #437 
* #448
> Enable checksum verification of dependencies

- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/frontend/KotlinCodeVerifier.kt
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/frontend/KotlinCoreEnvironmentTools.kt
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/sensors/AbstractKotlinSensorExecuteContext.kt
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/ast/AstPrinter.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/checks/ApiExtensionsKtTest.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/checks/FieldMatcherTest.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/checks/FunMatcherTest.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/frontend/KotlinASTTest.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/frontend/KotlinCoreEnvironmentToolsTest.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/frontend/KotlinSyntaxStructureTest.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/frontend/KotlinTreeTest.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/frontend/TextRangeTrackerTest.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/sensors/AbstractKotlinSensorTest.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/tools/AstPrinterTest.kt
- sonar-kotlin-metrics/src/test/java/org/sonarsource/kotlin/metrics/CyclomaticComplexityVisitorTest.kt
- sonar-kotlin-metrics/src/test/java/org/sonarsource/kotlin/metrics/IssueSuppressionVisitorTest.kt
- sonar-kotlin-metrics/src/test/java/org/sonarsource/kotlin/metrics/MetricVisitorTest.kt
- sonar-kotlin-metrics/src/test/java/org/sonarsource/kotlin/metrics/StatementsVisitorTest.kt
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/KotlinSensorTest.kt
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/cpd/CopyPasteDetectorTest.kt
- sonar-kotlin-test-api/src/main/java/org/sonarsource/kotlin/testapi/KotlinVerifier.kt
> Fix memory leaks in tests

- sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/EqualsOverriddenWithArrayFieldCheck.kt
> SONARKT-400 Migrate EqualsOverriddenWithArrayFieldCheck to kotlin-analysis-api

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/PullRequestClosed.yml
- .github/workflows/PullRequestCreated.yml
- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt
- sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/ReceivingIntentsCheck.kt
[SONARKT-408](https://sonarsource.atlassian.net/browse/SONARKT-408)
To review:
Make sure the files are the same as these
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml
https://raw.githubusercontent.com/SonarSource/sonar-dotnet-enterprise/refs/heads/master/.github/PULL_REQUEST_TEMPLATE.md?token=GHSAT0AAAAAACM3Q6EYDU5DNCGFOFCNBMAYZYSOQXA
Make sure that PullRequestCreated.yml has the correct Jira project on the last line
FYI: …
> SONARKT-408 Add Jira integration

- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt
- sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/UnencryptedDatabaseOnMobileCheck.kt
[SONARKT-423](https://sonarsource.atlassian.net/browse/SONARKT-423)
[SONARKT-423]: https://sonarsource.atlassian.net/browse/SONARKT-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-423 Migrate UnencryptedDatabaseOnMobileCheck to kotlin-analysis-api

- sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/AuthorisingNonAuthenticatedUsersCheck.kt
[SONARKT-423](https://sonarsource.atlassian.net/browse/SONARKT-423)
[SONARKT-423]: https://sonarsource.atlassian.net/browse/SONARKT-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-423 Migrate AuthorisingNonAuthenticatedUsersCheck to kotlin-analysis-api

- sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/RobustCryptographicKeysCheck.kt
> SONARKT-455 Migrate RobustCryptographicKeysCheck to kotlin-analysis-api

- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/FunMatcher.kt
- sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/ScheduledThreadPoolExecutorZeroCheck.kt
[SONARKT-501](https://sonarsource.atlassian.net/browse/SONARKT-501)
Part of 
SONARKT-423
[SONARKT-501]: https://sonarsource.atlassian.net/browse/SONARKT-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-501 Migrate ScheduledThreadPoolExecutorZeroCheck to kotlin-analysis-api

- sonar-kotlin-plugin/sonarpedia.json
- sonar-kotlin-plugin/src/main/resources/org/sonar/l10n/kotlin/rules/kotlin/S5332.json
- sonar-kotlin-plugin/src/main/resources/org/sonar/l10n/kotlin/rules/kotlin/S6293.json
[SONARKT-417](https://sonarsource.atlassian.net/browse/SONARKT-417)
[SONARKT-417]: https://sonarsource.atlassian.net/browse/SONARKT-417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-417 Update rules metadata

- sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/InjectableDispatchersCheck.kt
> SONARKT-454 Migrate InjectableDispatchersCheck to kotlin-analysis-api

- sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/ClearTextProtocolCheck.kt
[SONARKT-509](https://sonarsource.atlassian.net/browse/SONARKT-509)
Part of 
SONARKT-423
[SONARKT-509]: https://sonarsource.atlassian.net/browse/SONARKT-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-509 Migrate ClearTextProtocolCheck to kotlin-analysis-api

- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt
- sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/MainSafeCoroutinesCheck.kt
[SONARKT-554](https://sonarsource.atlassian.net/browse/SONARKT-554)
Part of 
SONARKT-532
[SONARKT-554]: https://sonarsource.atlassian.net/browse/SONARKT-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-554 Migrate MainSafeCoroutinesCheck to kotlin-analysis-api

- kotlin-checks-test-sources/src/main/kotlin/checks/CollectionCallingItselfCheckSample.kt
- sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/CollectionCallingItselfCheck.kt
[SONARKT-551](https://sonarsource.atlassian.net/browse/SONARKT-551)
[SONARKT-551]: https://sonarsource.atlassian.net/browse/SONARKT-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-551 Fix FNs in CollectionCallingItselfCheck (S2114)

- its/ruling/src/test/resources/expected/kotlin/kotlin/kotlin-S6524.json
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/FunMatcher.kt
- sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/CollectionShouldBeImmutableCheck.kt
[SONARKT-541](https://sonarsource.atlassian.net/browse/SONARKT-541)
Part of 
SONARKT-532
[SONARKT-541]: https://sonarsource.atlassian.net/browse/SONARKT-541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-541 Migrate CollectionShouldBeImmutableCheck to kotlin-analysis-api

- kotlin-checks-test-sources/src/main/kotlin/checks/UnnecessaryImportsCheckSample.kt
- sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/UnnecessaryImportsCheck.kt
[SONARKT-418](https://sonarsource.atlassian.net/browse/SONARKT-418)
[SONARKT-418]: https://sonarsource.atlassian.net/browse/SONARKT-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-418 Migrate UnnecessaryImportsCheck to kotlin-analysis-api

- kotlin-checks-test-sources/src/main/kotlin/sample/IssueNonSuppressionSample.kt
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/frontend/K1internals.java
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/frontend/K2.kt
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/frontend/KotlinCoreEnvironmentTools.kt
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/frontend/KotlinTree.kt
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/sensors/AbstractKotlinSensorExecuteContext.kt
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/visiting/KotlinFileVisitor.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/frontend/KotlinCoreEnvironmentToolsTest.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/frontend/KotlinSyntaxStructureTest.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/sensors/AbstractKotlinSensorTest.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/visiting/SonarKaSessionTest.kt
- sonar-kotlin-gradle/src/main/java/org/sonarsource/kotlin/gradle/KotlinGradleSensor.kt
- sonar-kotlin-metrics/src/test/java/org/sonarsource/kotlin/metrics/IssueSuppressionVisitorTest.kt
- sonar-kotlin-metrics/src/test/java/org/sonarsource/kotlin/metrics/MetricVisitorTest.kt
- sonar-kotlin-plugin/build.gradle.kts
- sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/plugin/KotlinSensor.kt
- sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/plugin/linking/WorkaroundForJarMinimization.java
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/KotlinSensorTest.kt
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/cpd/CopyPasteDetectorTest.kt
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/linking/WorkaroundForJarMinimizationTest.kt
- sonar-kotlin-test-api/src/main/java/org/sonarsource/kotlin/testapi/DummyInputFile.kt
- sonar-kotlin-test-api/src/main/java/org/sonarsource/kotlin/testapi/TestUtils.kt
[SONARKT-401](https://sonarsource.atlassian.net/browse/SONARKT-401)
[SONARKT-401]: https://sonarsource.atlassian.net/browse/SONARKT-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-401 Integrate K2 into plugin

- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/visiting/KotlinFileVisitor.kt
- sonar-kotlin-plugin/build.gradle.kts
- sonar-kotlin-plugin/proguard.txt
[SONARKT-608](https://sonarsource.atlassian.net/browse/SONARKT-608)
[SONARKT-608]: https://sonarsource.atlassian.net/browse/SONARKT-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-608 Reduce size of plugin

- its/ruling/src/test/resources/expected/kotlin/corda/kotlin-S6615.json
- its/ruling/src/test/resources/expected/kotlin/okio/kotlin-S6615.json
- kotlin-checks-test-sources/src/main/kotlin/checks/UselessAssignmentsCheckSample.kt
- sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/UselessAssignmentsCheck.kt
- sonar-kotlin-checks/src/test/java/org/sonarsource/kotlin/checks/UselessAssignmentsCheckTest.kt
[SONARKT-610](https://sonarsource.atlassian.net/browse/SONARKT-610)
[SONARKT-610]: https://sonarsource.atlassian.net/browse/SONARKT-610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-610 Fix FP in UselessAssignmentsCheck caused by regression in K2 compared to K1

- .cirrus.yml
- sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/plugin/KotlinPlugin.kt
[SONARKT-495](https://sonarsource.atlassian.net/browse/SONARKT-495)
[SONARKT-495]: https://sonarsource.atlassian.net/browse/SONARKT-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-495 Remove compatibility with SonarQube versions below 10.8

- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/frontend/KotlinFileContext.kt
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/sensors/AbstractKotlinSensor.kt
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/visiting/KotlinFileVisitor.kt
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/visiting/KtChecksVisitor.kt
- sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/sensors/AbstractKotlinSensorTest.kt
- sonar-kotlin-gradle/src/main/java/org/sonarsource/kotlin/gradle/KotlinGradleSensor.kt
- sonar-kotlin-metrics/src/test/java/org/sonarsource/kotlin/metrics/SyntaxHighlighterTest.kt
- sonar-kotlin-plugin/build.gradle.kts
- sonar-kotlin-plugin/proguard.txt
- sonar-kotlin-plugin/src/main/java/com/sonarsource/plugins/kotlin/api/KotlinPluginExtensionsProvider.java
- sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/plugin/KotlinPluginExtensions.kt
- sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/plugin/KotlinProfileDefinition.kt
- sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/plugin/KotlinRulesDefinition.kt
- sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/plugin/KotlinSensor.kt
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/CheckRegistrationTest.kt
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/DummyKotlinPluginExtensionsProvider.kt
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/KotlinProfileDefinitionTest.kt
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/KotlinRulesDefinitionTest.kt
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/KotlinSensorTest.kt
- sonar-kotlin-plugin/src/test/resources/org/sonar/l10n/kotlin/rules/kotlin/DummyRule.html
- sonar-kotlin-plugin/src/test/resources/org/sonar/l10n/kotlin/rules/kotlin/DummyRule.json
- sonar-kotlin-test-api/src/main/java/org/sonarsource/kotlin/testapi/AbstractSensorTest.kt
[SONARKT-620](https://sonarsource.atlassian.net/browse/SONARKT-620)
[SONARKT-620]: https://sonarsource.atlassian.net/browse/SONARKT-620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-620 Add integration points for implementation of taint analysis

- sonar-kotlin-api/build.gradle.kts
- sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/tools/PatchKotlinCompiler.kt
- sonar-kotlin-plugin/build.gradle.kts
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/AppScheduledExecutorServiceTest.kt
[SONARKT-401](https://sonarsource.atlassian.net/browse/SONARKT-401)
[SONARKT-401]: https://sonarsource.atlassian.net/browse/SONARKT-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-401 K2 should not create non-daemon threads

- sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/plugin/KotlinPlugin.kt
- sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/KotlinPluginTest.kt
[SONARKT-629](https://sonarsource.atlassian.net/browse/SONARKT-629)
[SONARKT-629]: https://sonarsource.atlassian.net/browse/SONARKT-629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-629 Fix SonarQube Cloud startup

- its/ruling/src/test/resources/expected/kotlin/kotlin-language-server/kotlin-S6474.json
- sonar-kotlin-gradle/src/main/java/org/sonarsource/kotlin/gradle/KotlinGradleSensor.kt
[SONARKT-594](https://sonarsource.atlassian.net/browse/SONARKT-594)
[SONARKT-594]: https://sonarsource.atlassian.net/browse/SONARKT-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-594 Run root-level Gradle checks (S6631 and S6474) on the root module only

- .github/workflows/PullRequestClosed.yml
[SONARKT-614](https://sonarsource.atlassian.net/browse/SONARKT-614)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SONARKT-614]: https://sonarsource.atlassian.net/browse/SONARKT-614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-614 Autoclose issues created by Jira integration

- .cirrus.yml
- .cirrus/clean-orchestrator-cache.sh
- gradle/verification-metadata.xml
- its/plugin/src/test/java/org/sonarsource/slang/TestsHelper.java
- its/ruling/src/test/java/org/sonarsource/slang/SlangRulingTest.java
- settings.gradle.kts
> SONARKT-671 Use lightweight Enterprise SQ edition in integration tests

- README.md
To make descriptions across Sonar repositories consistent and update to the new link.
> Update README.md description text
