SonarSource/sonar-kotlin

kotlin-checks-test-sources/src/main/kotlin/checks/ExternalAndroidStorageAccessCheckSample.kt, sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/checks/ExternalAndroidStorageAccessCheck.kt
Matching also on super types when calling methods that access Android external storage to avoid FNs when the method called actually belongs to a subtype of Context or Environment
=> SONARKT-68 Fixing S5324 FNs

sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/api/InputFileContext.kt, sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/converter/CommentAnnotationsAndTokenVisitor.kt, sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/plugin/InputFileContext.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/DummyInputFileContext.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/surefire/data/SurefireStaxHandlerTest.java, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/surefire/data/UnitTestClassReportTest.java, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/verifier/TestContext.kt
* Nullable type warning in InputFileContext
* Unused imports
* use isZero() for assertions
=> Fix quality flaw:

.cirrus.yml, export_ws_variables.sh, wss-unified-agent.config
The scan script expects a semver-like version number where the bugfix is
trimmed off in the end.
To this end, the build number (or 0 when it is not available) is
appended to the version number.
=> Fix version number generation for ws scan

kotlin-checks-test-sources/src/main/kotlin/checks/DeprecatedCodeUsedCheckSample.kt, sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/converter/KotlinCodeVerifier.kt, sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/converter/KotlinCoreEnvironmentTools.kt, sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/plugin/KotlinSensor.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/api/ApiExtensionsKtTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/api/FunMatcherTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/api/regex/TextRangeTrackerTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/converter/KotlinASTTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/converter/KotlinSyntaxStructureTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/converter/KotlinTreeTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/dev/AstPrinterTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/CopyPasteDetectorTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/CyclomaticComplexityVisitorTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/IssueSuppressionVisitorTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/KotlinPluginTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/KotlinSensorTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/MetricVisitorTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/StatementsVisitorTest.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/verifier/KotlinVerifier.kt, utils-kotlin/src/main/kotlin/org/sonarsource/kotlin/ast/AstPrinter.kt
Introduce property that users can set to specify the Kotlin source code version they would like to scan their code with.
=> SONARKT-15 Introduce Kotlin source version property

utils-kotlin/README.md
Just fixing links to the linter versions.
=> Fix link to linter versions in README

gradle.properties
Fix a bug where artifacts would be published without version number making it impossible to distinguish between build artifacts.
This would result in ITs in the CI the pipeline failing because the tests would run against mismatched versions of the kotlin analyzer.
=> Add missing -SNAPSHOT key to version number 

build.gradle.kts
Fix an issue where versions of the analyzer with an explicit bug fix number would have an extra `}` character added to them preventing them from being published in a repository and retrieved in later steps of the CI.
=> [FIX] Remove trailing artifact that messes up build number replacement

.cirrus.yml
The goal of this commit is to make sure we run integration tests against a relevant LTS version
=> Upgrade SQ version matrix to test against current LTS

.cirrus.yml
Since the artifacts produced on this branch are only meant to run on SQ 9.9, we can limit cycle waste by avoiding to test against unrelated versions.
=> Restrict ITs to run on 9.9 LTS

sonar-kotlin-plugin/build.gradle.kts
Requires upgrade of Gradle to at least 8.3 - see #433
=> Upgrade Shadow Gradle plugin to 8.3.1

build.gradle.kts, kotlin-checks-test-sources/build.gradle.kts
> 'kotlinOptions: KotlinJvmOptions' is deprecated.
> Please migrate to the compilerOptions DSL.
> More details are here: https://kotl.in/u1r8ln
=> Fix Kotlin Gradle plugin warning

sonar-kotlin-plugin/build.gradle.kts
This was overlooked during replacement of
"kotlin-compiler-embeddable" by "kotlin-compiler"
in d7a5cfd5b0a6d96fd23e25711cd2db5eca931c35.
=> SONARKT-399 Fix shadowJar configuration

sonar-kotlin-plugin/build.gradle.kts
This was overlooked in c60ff8f09a8c2eaa8fa286be68ca7a784276960d.
=> Aggregate coverage report should include `sonar-kotlin-test-api`

sonar-kotlin-api/build.gradle.kts
Otherwise execution of
./gradlew clean
./gradlew :sonar-kotlin-api:test
shows failures of `FunMatcherTest` and `KotlinTreeTest`.
=> `:sonar-kotlin-api:test` should depend on `:kotlin-checks-test-sources`

sonar-kotlin-checks/build.gradle.kts
Otherwise execution of
./gradlew clean
./gradlew :sonar-kotlin-checks:test
leads to test failures.
=> `:sonar-kotlin-checks:test` should depend on `:kotlin-checks-test-sources`

sonar-kotlin-checks/src/test/java/org/sonarsource/kotlin/checks/VarShouldBeValCheckTest.kt
VarShouldBeValCheckTest
`with partial semantics`
is duplicate of
`with k1 semantics`.
=> Remove duplicate test

sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ArgumentMatcher.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/CallAbstractCheck.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/FunMatcher.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/frontend/KotlinCoreEnvironmentTools.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/sensors/AbstractKotlinSensorExecuteContext.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/BiometricAuthWithoutCryptoCheck.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/EqualsMethodUsageCheck.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/EqualsOverridenWithHashCodeCheck.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/FinalFlowOperationCheck.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/IndexedAccessCheck.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/RedundantMethodsInDataClassesCheck.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/RunFinalizersCheck.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/SimplifiedPreconditionsCheck.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/StreamNotConsumedCheck.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/UnencryptedFilesInMobileApplicationsCheck.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/UnsuitedFindFunctionWithNullComparisonCheck.kt, sonar-kotlin-test-api/src/main/java/org/sonarsource/kotlin/testapi/TestUtils.kt
=> SONARKT-400 Migrate FunMatcher

its/plugin/src/test/java/org/sonarsource/slang/MeasuresTest.java
Related to https://sonarsource.atlassian.net/browse/SONAR-22876
=> SONAR-22876 Remove from integration tests assertions for `executable_lines_data` and `ncloc_data`

sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/ReceivingIntentsCheck.kt
=> Migrate ReceivingIntentsCheck to kotlin-analysis-api

sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/AndroidBroadcastingCheck.kt
=> SONARKT-423 Migrate AndroidBroadcastingCheck to kotlin-analysis-api

sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt, sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/checks/ApiExtensionsKtTest.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/DuplicateBranchCheck.kt
[SONARKT-423](https://sonarsource.atlassian.net/browse/SONARKT-423)
[SONARKT-423]: https://sonarsource.atlassian.net/browse/SONARKT-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-453 Migrate DuplicateBranchCheck to kotlin-analysis-api

gradle/verification-metadata.xml, its/plugin/src/test/java/org/sonarsource/slang/ExternalReportTest.java, its/plugin/src/test/java/org/sonarsource/slang/SonarLintTest.java, its/plugin/src/test/java/org/sonarsource/slang/TestBase.java, its/plugin/src/test/java/org/sonarsource/slang/TestsHelper.java, its/ruling/src/test/java/org/sonarsource/slang/SlangRulingTest.java, settings.gradle.kts, sonar-kotlin-metrics/src/main/java/org/sonarsource/kotlin/metrics/MetricVisitor.kt, sonar-kotlin-metrics/src/main/java/org/sonarsource/kotlin/metrics/TelemetryData.kt, sonar-kotlin-metrics/src/test/java/org/sonarsource/kotlin/metrics/MetricVisitorTest.kt, sonar-kotlin-metrics/src/test/java/org/sonarsource/kotlin/metrics/TelemetryDataTest.kt, sonar-kotlin-plugin/src/main/java/org/sonarsource/kotlin/plugin/KotlinSensor.kt, sonar-kotlin-plugin/src/test/java/org/sonarsource/kotlin/plugin/KotlinSensorTest.kt, sonar-kotlin-surefire/src/test/java/org/sonarsource/kotlin/surefire/KotlinResourcesLocatorTest.java
~**Do not merge**: the PR is based on https://github.com/SonarSource/sonar-kotlin/pull/522~
**Do not squash**: SONARKT-424 required Plugin API update, which is done on a dedicated commit
[SONARKT-424](https://sonarsource.atlassian.net/browse/SONARKT-424)
Telemetry data: https://dub01.online.tableau.com/#/site/sonarsource/views/SQ-V2Telemetry-byAnalysis/Detailedview?:iid=1
[SONARKT-424]: https://sonarsource.atlassian.net/browse/SONARKT-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DO NOT SQUASH] SONARKT-424 Kotlin android telemetry metric

kotlin-checks-test-sources/src/main/kotlin/checks/EqualsOverridenWithHashCodeCheckSample.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/FunMatcher.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/UnpredictableHashSaltCheck.kt
[SONARKT-494](https://sonarsource.atlassian.net/browse/SONARKT-494)
Part of 
SONARKT-423
[SONARKT-494]: https://sonarsource.atlassian.net/browse/SONARKT-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-494 Migrate UnpredictableHashSaltCheck to kotlin-analysis-api

sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/WebViewJavaScriptSupportCheck.kt
[SONARKT-503](https://sonarsource.atlassian.net/browse/SONARKT-503)
Part of 
SONARKT-423
[SONARKT-503]: https://sonarsource.atlassian.net/browse/SONARKT-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-503 Migrate WebViewJavaScriptSupportCheck to kotlin-analysis-api

sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/FunMatcher.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/WebViewsFileAccessCheck.kt
[SONARKT-500](https://sonarsource.atlassian.net/browse/SONARKT-500)
Part of 
SONARKT-423
[SONARKT-500]: https://sonarsource.atlassian.net/browse/SONARKT-500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-500 Migrate WebViewsFileAccessCheck to kotlin-analysis-api

kotlin-checks-test-sources/src/main/kotlin/checks/EqualsOverridenWithHashCodeCheckSample.kt, kotlin-checks-test-sources/src/main/kotlin/checks/SimplifySizeExpressionCheckSample.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/FunMatcher.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/CipherModeOperationCheck.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/UnpredictableHashSaltCheck.kt
[SONARKT-502](https://sonarsource.atlassian.net/browse/SONARKT-502)
Part of 
SONARKT-423
[SONARKT-502]: https://sonarsource.atlassian.net/browse/SONARKT-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-502 Migrate CipherModeOperationCheck to kotlin-analysis-api

sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/UnpredictableSecureRandomSaltCheck.kt
[SONARKT-505](https://sonarsource.atlassian.net/browse/SONARKT-505)
Part of 
SONARKT-423
[SONARKT-505]: https://sonarsource.atlassian.net/browse/SONARKT-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-505 Migrate UnpredictableSecureRandomSaltCheck to kotlin-analysis-api

sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/VerifiedServerHostnamesCheck.kt
[SONARKT-507](https://sonarsource.atlassian.net/browse/SONARKT-507)
Part of 
SONARKT-423
[SONARKT-507]: https://sonarsource.atlassian.net/browse/SONARKT-507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-507 Migrate VerifiedServerHostnamesCheck to kotlin-analysis-api

sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/FunMatcher.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/ExternalAndroidStorageAccessCheck.kt
[SONARKT-508](https://sonarsource.atlassian.net/browse/SONARKT-508)
Part of 
SONARKT-423
[SONARKT-508]: https://sonarsource.atlassian.net/browse/SONARKT-508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-508 Migrate ExternalAndroidStorageAccessCheck to kotlin-analysis-api

kotlin-checks-test-sources/src/main/kotlin/checks/DeprecatedCodeUsedCheckSample.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/frontend/KotlinFileContext.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/frontend/KtModuleProviderByCompilerConfiguration.java, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/DeprecatedCodeUsedCheck.kt
[SONARKT-535](https://sonarsource.atlassian.net/browse/SONARKT-535)
Part of 
SONARKT-532
[SONARKT-535]: https://sonarsource.atlassian.net/browse/SONARKT-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-535 Migrate DeprecatedCodeUsedCheck to kotlin-analysis-api

kotlin-checks-test-sources/src/main/kotlin/checks/DeprecatedCodeUsedCheckSample.kt, kotlin-checks-test-sources/src/main/kotlin/checks/UselessAssignmentsCheckSample.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/frontend/KotlinFileContext.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/frontend/KtModuleProviderByCompilerConfiguration.java, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/DeprecatedCodeUsedCheck.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/UselessAssignmentsCheck.kt
[SONARKT-537](https://sonarsource.atlassian.net/browse/SONARKT-537)
Part of 
SONARKT-532
[SONARKT-537]: https://sonarsource.atlassian.net/browse/SONARKT-537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-537 Migrate UselessAssignmentsCheck to kotlin-analysis-api

sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/VoidShouldBeUnitCheck.kt
[SONARKT-547](https://sonarsource.atlassian.net/browse/SONARKT-547)
Part of 
SONARKT-532
[SONARKT-547]: https://sonarsource.atlassian.net/browse/SONARKT-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-547 Migrate VoidShouldBeUnitCheck to kotlin-analysis-api

sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/EmptyLineRegexCheck.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/VerifiedServerHostnamesCheck.kt
[SONARKT-553](https://sonarsource.atlassian.net/browse/SONARKT-553)
Part of 
SONARKT-532
[SONARKT-553]: https://sonarsource.atlassian.net/browse/SONARKT-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-553 Migrate EmptyLineRegexCheck to kotlin-analysis-api

sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/MapValuesShouldBeAccessedSafelyCheck.kt
[SONARKT-493](https://sonarsource.atlassian.net/browse/SONARKT-493)
Part of 
SONARKT-423
[SONARKT-493]: https://sonarsource.atlassian.net/browse/SONARKT-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-493 Migrate MapValuesShouldBeAccessedSafelyCheck to kotlin-analysis-api

kotlin-checks-test-sources/src/main/kotlin/checks/StructuredConcurrencyPrinciplesCheckSample.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/StructuredConcurrencyPrinciplesCheck.kt
[SONARKT-462](https://sonarsource.atlassian.net/browse/SONARKT-462)
Part of 
SONARKT-423
[SONARKT-462]: https://sonarsource.atlassian.net/browse/SONARKT-462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-462 Migrate StructuredConcurrencyPrinciplesCheck to kotlin-analysis-api

sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/EqualsArgumentTypeCheck.kt
=> SONARKT-458 Migrate EqualsArgumentTypeCheck to kotlin-analysis-api

sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/CollectionCallingItselfCheck.kt
[SONARKT-546](https://sonarsource.atlassian.net/browse/SONARKT-546)
Part of 
SONARKT-532
[SONARKT-546]: https://sonarsource.atlassian.net/browse/SONARKT-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-546 Migrate CollectionCallingItselfCheck to kotlin-analysis-api

its/ruling/src/test/resources/expected/kotlin/kotlin/kotlin-S6619.json, kotlin-checks-test-sources/src/main/files/non-compiling/checks/UselessNullCheckCheckSampleNonCompiling.kt, kotlin-checks-test-sources/src/main/kotlin/checks/UselessNullCheckCheckSample.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/frontend/K1internals.java, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/UselessNullCheckCheck.kt, sonar-kotlin-checks/src/test/java/org/sonarsource/kotlin/checks/UselessNullCheckCheckTest.kt
[SONARKT-544](https://sonarsource.atlassian.net/browse/SONARKT-544)
Part of 
SONARKT-532
Added test case is not previously existing FP but part of rewrite.
[SONARKT-544]: https://sonarsource.atlassian.net/browse/SONARKT-544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-544 Migrate UselessNullCheckCheck to kotlin-analysis-api

its/ruling/src/test/resources/expected/kotlin/kotlin/kotlin-S6514.json, its/ruling/src/test/resources/expected/kotlin/okio/kotlin-S6514.json, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/ApiExtensions.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/DelegationPatternCheck.kt
[SONARKT-552](https://sonarsource.atlassian.net/browse/SONARKT-552)
Part of 
SONARKT-532
[SONARKT-552]: https://sonarsource.atlassian.net/browse/SONARKT-552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-552 Migrate DelegationPatternCheck to kotlin-analysis-api

kotlin-checks-test-sources/src/main/kotlin/checks/RedundantTypeCastsCheckSample.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/RedundantTypeCastsCheck.kt
[SONARKT-539](https://sonarsource.atlassian.net/browse/SONARKT-539)
Part of 
SONARKT-532
[SONARKT-539]: https://sonarsource.atlassian.net/browse/SONARKT-539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-539 Migrate RedundantTypeCastsCheck to kotlin-analysis-api

kotlin-checks-test-sources/src/main/java/android/net/http/SslCertificate.java, kotlin-checks-test-sources/src/main/java/android/net/http/SslError.java, kotlin-checks-test-sources/src/main/java/android/os/Handler.java, kotlin-checks-test-sources/src/main/java/android/os/Handler.kt, kotlin-checks-test-sources/src/main/java/android/webkit/SslErrorHandler.java, kotlin-checks-test-sources/src/main/java/android/webkit/WebViewClient.java, kotlin-checks-test-sources/src/main/kotlin/checks/ServerCertificateCheckSample.kt, kotlin-checks-test-sources/src/main/kotlin/checks/ServerCertificateCheckSampleNoSemantics.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/ServerCertificateCheck.kt, sonar-kotlin-plugin/src/main/resources/org/sonar/l10n/kotlin/rules/kotlin/S4830.html
[SONARKT-569](https://sonarsource.atlassian.net/browse/SONARKT-569)
[SONARKT-569]: https://sonarsource.atlassian.net/browse/SONARKT-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARKT-569 Add support for WebViews to S4830

gradle.properties, gradle/verification-metadata.xml, its/ruling/src/test/resources/expected/kotlin/corda/kotlin-S1874.json, its/ruling/src/test/resources/expected/kotlin/kotlin/kotlin-S1128.json, its/ruling/src/test/resources/expected/kotlin/kotlin/kotlin-S6619.json, kotlin-checks-test-sources/src/main/kotlin/checks/DeprecatedCodeUsedCheckSample.kt, kotlin-checks-test-sources/src/main/kotlin/checks/UnnecessaryImportsCheckSample.kt, kotlin-checks-test-sources/src/main/kotlin/checks/UnnecessaryImportsCheckSampleNoSemantics.kt, kotlin-checks-test-sources/src/main/kotlin/checks/UnnecessaryImportsCheckSamplePartialSemantics.kt, kotlin-checks-test-sources/src/main/kotlin/checks/UselessNullCheckCheckSample.kt, kotlin-checks-test-sources/src/main/kotlin/otherpackage/Importable.kt, kotlin-checks-test-sources/src/main/kotlin/sample/functions.kt, sonar-kotlin-api/src/main/java/org/sonarsource/kotlin/api/checks/FunMatcher.kt, sonar-kotlin-api/src/test/java/org/sonarsource/kotlin/api/checks/FunMatcherTest.kt, sonar-kotlin-plugin/build.gradle.kts, sonar-kotlin-plugin/proguard.txt
[SONARKT-550](https://sonarsource.atlassian.net/browse/SONARKT-550)
`v2.1.20` came with a change of the behavior of `containingClassId` specifically for constructor aliases such as `kotlin.XYZException`. 
See the following change (`git diff v2.1.10 v2.1.20 | grep -B 10 -A 10 containingClassId`):
```
@@ -80,6 +81,7 @@ internal class KaFirConstructorSymbol private constructor(
override val containingClassId: ClassId?
get() = withValidityAssertion {
backingPsi?.getContainingClassOrObject()?.getClassId()
+                ?: firSymbol.typeAliasForConstructor?.classId?.takeUnless { it.isLocal }
?: firSymbol.containingClassLookupTag()?.classId?.takeUnless { it.isLocal }
}
--
```
So `FunMatcher.getActualQualifier` for constructors (i.e. `KaConstructorSymbol`, which never have `callableId`, nor …
=> SONARKT-550 Upgrade Kotlin compiler to 2.1.20

kotlin-checks-test-sources/src/main/kotlin/checks/SuspendingFunCallerDispatcherCheckSample.kt, sonar-kotlin-checks/src/main/java/org/sonarsource/kotlin/checks/SuspendingFunCallerDispatcherCheck.kt
A regression occurred in 166b85190b9b95ee6d0c763752271fe845a9d218, which causes this rule to raise whenever `launch`, `async` or `withContext` is used with one suspending function, regardless of if a `Dispatcher` is set or not.
A user [raised the issue](https://community.sonarsource.com/t/kotlin-s6311-raises-a-false-positive-for-android-viewmodel-coroutines-usage/138038) a few days ago. This PR is a simple fix for the issue, and also adds the [compliant sample](https://sonarsource.github.io/rspec/#/rspec/S6311) as a test case.
=> SONARKT-644 Fix FP in S6311 when no Dispatcher is used explicitly

.cirrus/clean-orchestrator-cache.sh
The sort command options used to select the sonar-application to keep were not working as expected.
Part of BUILD-7780
- cleanup orchestrator cache
=> BUILD-7780 Fix clean-orchestrator-cache.sh

.github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml, .github/workflows/dogfood.yml, .github/workflows/releasability.yaml, .github/workflows/slack_notify.yml
Migrates public repository workflows from standard GitHub-hosted runners to **Large Runners**
(`ubuntu-latest` → `ubuntu-latest-large`, etc.).
See [BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073) for details.
[BUILD-8073]: https://sonarsource.atlassian.net/browse/BUILD-8073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BUILD-8073 Migrate public repositories workflows to large runners

.github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml, .github/workflows/dogfood.yml, .github/workflows/releasability.yaml, .github/workflows/slack_notify.yml
This PR updates GitHub Actions workflows to use our new standardized runner naming convention.
- Updates runner names in workflow files to new standardized format
- No functional changes to your CI/CD pipelines
- All existing functionality remains identical
| Old Runner | New Runner |
|------------|------------|
| sonar-runner-large | github-ubuntu-latest-s |
| ubuntu-latest-large | github-ubuntu-latest-s |
| windows-latest-large | github-windows-latest-s |
| ubuntu-24.04-large | github-ubuntu-latest-s |
| sonar-runner-large-arm | github-ubuntu-24.04-arm-s |
| ubuntu-24.04-arm-large | github-ubuntu-24.04-arm-s |
1. Review the changes in this PR
2. Merge when ready - no additional action required
3. Old runners will remain available during transition
For more details about GitHub Actions …
=> BUILD-8875 Migrate to standardized GitHub runner names
